### ISSUE TITLE
Use native logo function

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/dublin#11]
The theme is using custom logo field instead of the built-in option.

**Comment by rodica-andronache** [comment]
cc @HardeepAsrani

**Comment by HardeepAsrani** [comment]
@rodica-andronache Why are you checking the logo twice? has_custom_logo does that already.

**Comment by rodica-andronache** [comment]
@HardeepAsrani with your code, I got a broken image as a logo, because `echo esc_url(get_theme_mod('custom_logo')` returns an integer, not a URL. That's why I made those changes. Try by yourself and let me know. I might be wrong

**Comment by HardeepAsrani** [comment]
@rodica-andronache I remember wrapping that with `attachment_url_to_postid()` but looks like I forgot to commit it. Thanks for the fix. :)
